config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end

  post "/graphql", to: "graphql#execute"
  mount Motor::Admin => '/motor_admin'
  resources :stocks
  resources :colors
  resources :car_models
  resources :manufacturers

  root "stocks#index"
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :car_model
  belongs_to :color
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: %i[ show edit update destroy ]

  # GET /stocks or /stocks.json
  def index
    @stocks = Stock.all
  end

  # GET /stocks/1 or /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks or /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to stock_url(@stock), notice: "Stock was successfully created." }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1 or /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to stock_url(@stock), notice: "Stock was successfully updated." }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1 or /stocks/1.json
  def destroy
    @stock.destroy

    respond_to do |format|
      format.html { redirect_to stocks_url, notice: "Stock was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def stock_params
      params.require(:stock).permit(:car_model_id, :color_id, :milage, :cost, :price)
    end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/_form.html.erb
<%= form_with(model: stock) do |form| %>
  <% if stock.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
        <% stock.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :car_model_id, style: "display: block" %>
    <%= form.number_field :car_model_id %>
  </div>

  <div>
    <%= form.label :color_id, style: "display: block" %>
    <%= form.number_field :color_id %>
  </div>

  <div>
    <%= form.label :milage, style: "display: block" %>
    <%= form.number_field :milage %>
  </div>

  <div>
    <%= form.label :cost, style: "display: block" %>
    <%= form.number_field :cost %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/stocks/_stock.html.erb
<div id="<%= dom_id stock %>">
  <p>
    <strong>Car model:</strong>
    <%= stock.car_model_id %>
  </p>

  <p>
    <strong>Color:</strong>
    <%= stock.color_id %>
  </p>

  <p>
    <strong>Milage:</strong>
    <%= stock.milage %>
  </p>

  <p>
    <strong>Cost:</strong>
    <%= stock.cost %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= stock.price %>
  </p>

</div>

app/views/stocks/edit.html.erb
<h1>Editing stock</h1>

<%= render "form", stock: @stock %>

<br>

<div>
  <%= link_to "Show this stock", @stock %> |
  <%= link_to "Back to stocks", stocks_path %>
</div>

app/views/stocks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Stocks</h1>

<div id="stocks">
  <% @stocks.each do |stock| %>
    <%= render stock %>
    <p>
      <%= link_to "Show this stock", stock %>
    </p>
  <% end %>
</div>

<%= link_to "New stock", new_stock_path %>

app/views/stocks/new.html.erb
<h1>New stock</h1>

<%= render "form", stock: @stock %>

<br>

<div>
  <%= link_to "Back to stocks", stocks_path %>
</div>

app/views/stocks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @stock %>

<div>
  <%= link_to "Edit this stock", edit_stock_path(@stock) %> |
  <%= link_to "Back to stocks", stocks_path %>

  <%= button_to "Destroy this stock", @stock, method: :delete %>
</div>