config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end

  post "/graphql", to: "graphql#execute"
  mount Motor::Admin => '/motor_admin'
  resources :stocks
  resources :colors
  resources :car_models
  resources :manufacturers

  root "stocks#index"
end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
  has_many :car_models
end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController
  before_action :set_manufacturer, only: %i[ show edit update destroy ]

  # GET /manufacturers or /manufacturers.json
  def index
    @manufacturers = Manufacturer.all
  end

  # GET /manufacturers/1 or /manufacturers/1.json
  def show
  end

  # GET /manufacturers/new
  def new
    @manufacturer = Manufacturer.new
  end

  # GET /manufacturers/1/edit
  def edit
  end

  # POST /manufacturers or /manufacturers.json
  def create
    @manufacturer = Manufacturer.new(manufacturer_params)

    respond_to do |format|
      if @manufacturer.save
        format.html { redirect_to manufacturer_url(@manufacturer), notice: "Manufacturer was successfully created." }
        format.json { render :show, status: :created, location: @manufacturer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @manufacturer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /manufacturers/1 or /manufacturers/1.json
  def update
    respond_to do |format|
      if @manufacturer.update(manufacturer_params)
        format.html { redirect_to manufacturer_url(@manufacturer), notice: "Manufacturer was successfully updated." }
        format.json { render :show, status: :ok, location: @manufacturer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @manufacturer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /manufacturers/1 or /manufacturers/1.json
  def destroy
    @manufacturer.destroy

    respond_to do |format|
      format.html { redirect_to manufacturers_url, notice: "Manufacturer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manufacturer
      @manufacturer = Manufacturer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def manufacturer_params
      params.require(:manufacturer).permit(:name)
    end
end

app/helpers/manufacturers_helper.rb
module ManufacturersHelper
end

app/views/manufacturers/_form.html.erb
<%= form_with(model: manufacturer) do |form| %>
  <% if manufacturer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(manufacturer.errors.count, "error") %> prohibited this manufacturer from being saved:</h2>

      <ul>
        <% manufacturer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/manufacturers/_manufacturer.html.erb
<div id="<%= dom_id manufacturer %>">
  <p>
    <strong>Name:</strong>
    <%= manufacturer.name %>
  </p>

</div>

app/views/manufacturers/edit.html.erb
<h1>Editing manufacturer</h1>

<%= render "form", manufacturer: @manufacturer %>

<br>

<div>
  <%= link_to "Show this manufacturer", @manufacturer %> |
  <%= link_to "Back to manufacturers", manufacturers_path %>
</div>

app/views/manufacturers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Manufacturers</h1>

<div id="manufacturers">
  <% @manufacturers.each do |manufacturer| %>
    <%= render manufacturer %>
    <p>
      <%= link_to "Show this manufacturer", manufacturer %>
    </p>
  <% end %>
</div>

<%= link_to "New manufacturer", new_manufacturer_path %>

app/views/manufacturers/new.html.erb
<h1>New manufacturer</h1>

<%= render "form", manufacturer: @manufacturer %>

<br>

<div>
  <%= link_to "Back to manufacturers", manufacturers_path %>
</div>

app/views/manufacturers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @manufacturer %>

<div>
  <%= link_to "Edit this manufacturer", edit_manufacturer_path(@manufacturer) %> |
  <%= link_to "Back to manufacturers", manufacturers_path %>

  <%= button_to "Destroy this manufacturer", @manufacturer, method: :delete %>
</div>