config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end

  post "/graphql", to: "graphql#execute"
  mount Motor::Admin => '/motor_admin'
  resources :stocks
  resources :colors
  resources :car_models
  resources :manufacturers

  root "stocks#index"
end

app/models/car_model.rb
class CarModel < ApplicationRecord
  belongs_to :manufacturer
end

app/controllers/car_models_controller.rb
class CarModelsController < ApplicationController
  before_action :set_car_model, only: %i[ show edit update destroy ]

  # GET /car_models or /car_models.json
  def index
    @car_models = CarModel.all
  end

  # GET /car_models/1 or /car_models/1.json
  def show
  end

  # GET /car_models/new
  def new
    @car_model = CarModel.new
  end

  # GET /car_models/1/edit
  def edit
  end

  # POST /car_models or /car_models.json
  def create
    @car_model = CarModel.new(car_model_params)

    respond_to do |format|
      if @car_model.save
        format.html { redirect_to car_model_url(@car_model), notice: "Car model was successfully created." }
        format.json { render :show, status: :created, location: @car_model }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @car_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /car_models/1 or /car_models/1.json
  def update
    respond_to do |format|
      if @car_model.update(car_model_params)
        format.html { redirect_to car_model_url(@car_model), notice: "Car model was successfully updated." }
        format.json { render :show, status: :ok, location: @car_model }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @car_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /car_models/1 or /car_models/1.json
  def destroy
    @car_model.destroy

    respond_to do |format|
      format.html { redirect_to car_models_url, notice: "Car model was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car_model
      @car_model = CarModel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def car_model_params
      params.require(:car_model).permit(:name, :manufacturer_id)
    end
end

app/helpers/car_models_helper.rb
module CarModelsHelper
end

app/views/car_models/_car_model.html.erb
<div id="<%= dom_id car_model %>">
  <p>
    <strong>Name:</strong>
    <%= car_model.name %>
  </p>

  <p>
    <strong>Manufacturer:</strong>
    <%= car_model.manufacturer_id %>
  </p>

</div>

app/views/car_models/_form.html.erb
<%= form_with(model: car_model) do |form| %>
  <% if car_model.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(car_model.errors.count, "error") %> prohibited this car_model from being saved:</h2>

      <ul>
        <% car_model.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :manufacturer_id, style: "display: block" %>
    <%= form.number_field :manufacturer_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/car_models/edit.html.erb
<h1>Editing car model</h1>

<%= render "form", car_model: @car_model %>

<br>

<div>
  <%= link_to "Show this car model", @car_model %> |
  <%= link_to "Back to car models", car_models_path %>
</div>

app/views/car_models/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Car models</h1>

<div id="car_models">
  <% @car_models.each do |car_model| %>
    <%= render car_model %>
    <p>
      <%= link_to "Show this car model", car_model %>
    </p>
  <% end %>
</div>

<%= link_to "New car model", new_car_model_path %>

app/views/car_models/new.html.erb
<h1>New car model</h1>

<%= render "form", car_model: @car_model %>

<br>

<div>
  <%= link_to "Back to car models", car_models_path %>
</div>

app/views/car_models/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @car_model %>

<div>
  <%= link_to "Edit this car model", edit_car_model_path(@car_model) %> |
  <%= link_to "Back to car models", car_models_path %>

  <%= button_to "Destroy this car model", @car_model, method: :delete %>
</div>